### ISSUE TITLE
Where I can get the dataset for testing?

### ISSUE THREAD

**Issue by JafferWilson** [huajianjiu/Stochastic_PCBOW#1]
I have tried the steps:
```
make
./demo-word.sh
Read External Paraphrases: ../SNetSG_ts/ppdb_2_EFR.txt
Starting training using file text8
ERROR: training data file not found!

real 0m0.039s
user 0m0.012s
sys 0m0.024s
Input file not found
```
I think the dataset is what I am missing. Kindly help me.

**Comment by yuanzhiKe** [comment]
Hello, @JafferWilson . You can get the text8 dataset by wget http://mattmahoney.net/dc/text8.zip

**Comment by JafferWilson** [comment]
Where I need to give this input file?

**Comment by yuanzhiKe** [comment]
@JafferWilson You can replace the path in the bash script with your file's.

**Comment by JafferWilson** [comment]
@huajianjiu Please can you show how to change the line? Do I need to replace only the test8 or how I can give the input? Please guide me.

**Comment by yuanzhiKe** [comment]
@JafferWilson 
An example if you put text8 and a paraphrase table caleed ppdb_2.txt in the root folder of the codes: 
`time fuzzypp_word2vec -train text8 -output vectors_ppdb2 -read-paraphrases ppdb_2.txt -cbow 1 -size 200 -window 8 -negative 25 -sample 1e-4 -threads 20 -binary 1 -iter 15 -dropout 1`

**Comment by JafferWilson** [comment]
Can I replace ppdb_2.txt with the downloaded PPDB file ppdb-2.0s-all?

**Comment by yuanzhiKe** [comment]
@JafferWilson Certainlly.

**Comment by JafferWilson** [comment]
Thank you my friend.. really hepful.. :)
